AWSTemplateFormatVersion: 2010-09-09
Description: >-
  GuardDuty with email alert. 
  **WARNING** You will be billed for the AWS resources created if you create a 
  stack from this template.

  Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  
  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  A copy of the License is located at
  
      http://www.apache.org/licenses/LICENSE-2.0
  
  or in the "license" file accompanying this file. This file is distributed 
  on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
  express or implied. See the License for the specific language governing 
  permissions and limitations under the License.
Parameters:
  EmailAddress:
    Type: String
    Default: 'someone@example.com'
    Description: Enter the email address that will receive the alerts
  SNSTopicName:
    Type: String
    Default: 'GuardDuty-Email'
    Description: Enter the name of the SNS topic that will send the email alerts
  CWEventId:
    Type: String
    Default: 'GuardDuty-Email'
    Description: Enter the ID of the CloudWatch Event
Resources:
  GDDetector:
    Type: 'AWS::GuardDuty::Detector'
    Properties:
      Enable: true
  GDSNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: !Join 
        - '-'
        - - !Ref SNSTopicName
  GDCWEvent:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: GuardDuty Email Event
      EventPattern:
        source:
          - aws.guardduty
        detail-type:
          - GuardDuty Finding
      State: ENABLED
      Targets:
        - Arn: !Ref GDSNSTopic
          Id: !Ref CWEventId
  GDSNSSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Endpoint: !Ref EmailAddress
      Protocol: email
      TopicArn: !Ref GDSNSTopic
