name: 'CFN-NAG check via Github Actions'


on: [push]

jobs:
  Cloudformation-checker:
    name: Check CFN security concerns
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Removing linting for now... not sure how helpful it is
      # - name: cfn-lint-action
      #   uses: docker://ghcr.io/scottbrenner/cfn-lint-action:master
      #   with:
      #     args: "static/**/*.yaml"
      - name: cfn-nag-action
        uses: stelligent/cfn_nag@master
        with:
          input_path: "static"
          extra_args: --ignore-fatal
      - name: cfn-lint-notification
        if: failure()
        uses: ros-tooling/action-amazon-chime@master
        with:
          message: |
            :rotating_light:
            ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
            Link to GitHub Action run: https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks
            :rotating_light:
          webhook: ${{ secrets.RoomWebHookUrl }}

      # - name: cfn-nag-action
      #   uses: stelligent/cfn_nag@v0.5.48
      #   with:
      #     args: '--input-path cloudformation/
