# This is a basic workflow to help you get started with Actions

name: PRODUCTION WA Labs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: ros-tooling/action-amazon-chime@master
        with:
          message: |
            [${{ github.workflow }}] ${{ github.actor}} did a [${{ github.event_name }}] on master branch.
          webhook: ${{ secrets.RoomWebHookUrl }}

          # The chat room webhook URL can be created using Chime:
          # See https://docs.aws.amazon.com/chime/latest/ug/webhooks.html
          # It is recommended to store the webhook URL as a secret, to avoid letting unknown user spam your chat room.
          # See https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables
